Repository aditya-an1l/convex, pull requests merged in 2025-05, with the labels that each got.

#3 Add `.gitignore` file
  .gitignore
Labels: enhancement

#5 Add `CONTRIBUTING.md` + Documentation
  CONTRIBUTING.md
  README.md
Labels: documentation

#6 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#8 7/core/add parser logic
  backend/README.md
  backend/language_packs/hindi.json
  backend/parser.py
Labels: core

#13 Add and update contribution guidelines, commit message standards, and code of conduct
  CODE_OF_CONDUCT.md
  COMMIT_MESSAGE_GUIDELINES.md
  CONTRIBUTING.md
Labels: documentation

#22 14/core/implement translator
  backend/demo/input_hindi.py
  backend/executor.py
  backend/parsed_code/demo.py
  backend/translator.py
Labels: core
